<?php

namespace Tests\Feature;

use App\Models\DocumentType;
use App\Models\Employee;
use App\Models\User;
use App\Notifications\DocumentExpiryAlert;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Notification;
use Tests\TestCase;

class ExpiryAlertsTest extends TestCase
{
    use RefreshDatabase;

    public function test_alert_fires_once_for_document_inside_lead_time(): void
    {
        Notification::fake();
        $this->seed();

        $employee = Employee::where('company_id', 1)->firstOrFail();
        $type = DocumentType::where('key', 'iqama')->firstOrFail(); // [90, 60, 30]

        $document = $employee->documents()->create([
            'document_type_id' => $type->id,
            'expiry_date' => now()->addDays(25)->toDateString(),
        ]);

        $this->artisan('hr:send-expiry-alerts')->assertSuccessful();

        $admin = User::where('email', 'admin@hr.local')->firstOrFail();
        $hr1 = User::where('email', 'hr1@hr.local')->firstOrFail();
        $hr2 = User::where('email', 'hr2@hr.local')->firstOrFail();

        $forThisDocument = fn (DocumentExpiryAlert $alert) => $alert->document->id === $document->id;

        Notification::assertSentTo($admin, DocumentExpiryAlert::class, $forThisDocument);
        Notification::assertSentTo($hr1, DocumentExpiryAlert::class, $forThisDocument);
        // hr2 belongs to company 2 only — must not be alerted for company 1.
        Notification::assertNotSentTo($hr2, DocumentExpiryAlert::class, $forThisDocument);

        // All crossed thresholds (90/60/30 at 25 days left) are consumed at once.
        $this->assertSame([30, 60, 90], $document->expiryAlerts()->orderBy('threshold_days')->pluck('threshold_days')->all());
    }

    public function test_alert_does_not_refire_on_next_run(): void
    {
        $this->seed();

        $employee = Employee::where('company_id', 1)->firstOrFail();
        $type = DocumentType::where('key', 'medical_insurance')->firstOrFail(); // [30, 15]

        $employee->documents()->create([
            'document_type_id' => $type->id,
            'expiry_date' => now()->addDays(10)->toDateString(),
        ]);

        $this->artisan('hr:send-expiry-alerts')->assertSuccessful();

        Notification::fake();
        $this->artisan('hr:send-expiry-alerts')->assertSuccessful();

        Notification::assertNothingSent();
    }

    public function test_document_outside_lead_time_does_not_alert(): void
    {
        Notification::fake();
        $this->seed();

        $employee = Employee::where('company_id', 1)->firstOrFail();
        $type = DocumentType::where('key', 'medical_insurance')->firstOrFail(); // [30, 15]

        $employee->documents()->create([
            'document_type_id' => $type->id,
            'expiry_date' => now()->addDays(120)->toDateString(),
        ]);

        // Clear alerts generated by other seeded documents, then assert
        // this specific far-future document produced none.
        $this->artisan('hr:send-expiry-alerts')->assertSuccessful();

        $document = $employee->documents()->latest('id')->firstOrFail();
        $this->assertSame(0, $document->expiryAlerts()->count());
    }

    public function test_in_app_notification_lands_in_database_and_bell(): void
    {
        $this->seed();

        $employee = Employee::where('company_id', 1)->firstOrFail();
        $type = DocumentType::where('key', 'iqama')->firstOrFail();

        $document = $employee->documents()->create([
            'document_type_id' => $type->id,
            'expiry_date' => now()->addDays(5)->toDateString(),
        ]);

        $this->artisan('hr:send-expiry-alerts')->assertSuccessful();

        $admin = User::where('email', 'admin@hr.local')->firstOrFail();
        $this->assertGreaterThan(0, $admin->unreadNotifications()->count());

        $notification = $admin->unreadNotifications()
            ->get()
            ->first(fn ($item) => ($item->data['document_id'] ?? null) === $document->id);

        $this->assertNotNull($notification);
        $this->assertSame('document_expiry', $notification->data['kind']);
        $this->assertStringContainsString($employee->name_ar, $notification->data['message_ar']);

        $this->actingAs($admin)->get(route('dashboard'))->assertOk();

        $this->actingAs($admin)->post(route('notifications.read-all'))->assertRedirect();
        $this->assertSame(0, $admin->fresh()->unreadNotifications()->count());
    }
}
